version: '3'
services:
  wordpress:
    volumes:
      - .:/workspace
    environment:
      WORDPRESS_DEBUG: 1
      WORDPRESS_CONFIG_EXTRA: |
        define('DOMAIN_CURRENT_SITE', 'localhost');
        define('PATH_CURRENT_SITE', '/');
        define( 'WP_DEBUG_LOG', true );
 